# Generated by Django 3.0.4 on 2020-03-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200330_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='location_zip',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
